### ISSUE TITLE
Does it require .Net Framework 3.5?

### ISSUE THREAD

**Issue by planist** [cubewise-code/tm1kill#2]
Hello, When I try to use tm1kill, it pops up Windows installed and tries to install .Net Framework 3.5 and fails to do so. Hence tm1kill did not work. Any ideas?
My Version PA 2.0.7 on Windows Server 2016.

**Comment by cubewise-tryan** [comment]
Hi @planist,

Yes, TM1Kill is running .NET 3.5. It needs to be installed for it to run.
